java_library(
    name = "file_configuration",
    srcs = [
        "com/snowp/fw_control_plane/FileConfigurationManagerTest.java"
    ]
)

java_test(
    name = "file_configuration_test",
    runtime_deps = [
        ':file_configuration'
        ],
)